In [1]:
import tensorflow as tf

In [2]:
mnist=tf.keras.datasets.mnist

In [3]:
mnist

<module 'keras.api._v2.keras.datasets.mnist' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\mnist\\__init__.py'>

In [5]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11501568/11490434 [==============================] - 1s 0us/step


In [7]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model=tf.keras.models.Sequential([ tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)])

In [9]:
model

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.10960059, -0.16331844,  0.08339661,  0.08547702,  0.31411928,
        -0.19941211, -0.23181894,  0.21691321, -0.18591753,  0.66802573]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.08202351, 0.07773364, 0.09948462, 0.0996918 , 0.12530187,
        0.07497798, 0.07258713, 0.11369503, 0.07599663, 0.17850779]],
      dtype=float32)

In [13]:
tf.keras.losses.BinaryCrossentropy(
    from_logits=False,
    label_smoothing=0,
    axis=-1,
    reduction="auto",
    name="binary_crossentropy",
)

In [14]:
 # Example 1: (batch_size = 1, number of samples = 4)  
y_true = [0, 1, 0, 0]
y_pred = [-18.6, 0.51, 2.94, -12.8]
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
bce(y_true, y_pred).numpy()


0.865458

In [25]:
# Example 2: (batch_size = 2, number of samples = 4)  
y_true = [[0, 1], [0, 0]]
y_pred = [[-18.6, 0.51], [2.94, -12.8]]
# Using default 'auto'/'sum_over_batch_size' reduction type.  
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
bce(y_true, y_pred).numpy()
0.865

0.865

In [26]:
# Using 'sample_weight' attribute  
bce(y_true, y_pred, sample_weight=[0.8, 0.2]).numpy()

0.2436386

0.2436386

In [38]:
# Using 'sum' reduction` type.  
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True,
reduction=tf.keras.losses.Reduction.SUM)
bce(y_true, y_pred).numpy()


1.730916

In [39]:
# Using 'none' reduction type.  
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True,
     reduction=tf.keras.losses.Reduction.NONE)
bce(y_true, y_pred).numpy()


array([0.23515666, 1.4957594 ], dtype=float32)

In [33]:
# Make the following updates to the above "Recommended Usage" section  
# 1. Set `from_logits=False`  Default
tf.keras.losses.BinaryCrossentropy() # OR ...('from_logits=False')
# 2. Update `y_pred` to use probabilities instead of logits  
y_pred = [0.6, 0.3, 0.2, 0.8] # OR [[0.6, 0.3], [0.2, 0.8]]

0.18808000000000002

In [40]:
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
# Using 'auto'/'sum_over_batch_size' reduction type.  
cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true, y_pred).numpy()


1.1769392

In [41]:
cce(y_true, y_pred, sample_weight=tf.constant([0.3, 0.7])).numpy()

0.8135988

In [43]:
cce = tf.keras.losses.CategoricalCrossentropy(
reduction=tf.keras.losses.Reduction.SUM)
cce(y_true, y_pred).numpy()

2.3538785

In [44]:
 cce = tf.keras.losses.CategoricalCrossentropy(
     reduction=tf.keras.losses.Reduction.NONE)
 cce(y_true, y_pred).numpy()

array([0.05129331, 2.3025851 ], dtype=float32)

In [45]:
tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False, reduction="auto", name="sparse_categorical_crossentropy"
)

In [47]:
y_true = [1, 2]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
# Using 'auto'/'sum_over_batch_size' reduction type.  
scce = tf.keras.losses.SparseCategoricalCrossentropy()
scce(y_true, y_pred).numpy()

1.1769392

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [49]:
tf.nn.softmax(predictions).numpy()

array([[0.08202351, 0.07773364, 0.09948462, 0.0996918 , 0.12530187,
        0.07497798, 0.07258713, 0.11369503, 0.07599663, 0.17850779]],
      dtype=float32)

In [50]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [51]:
loss_fn(y_train[:1], predictions).numpy()

2.590561

In [53]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [54]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2951 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1421 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1076 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0872 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0733 - accuracy: 0.9773


In [55]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0755 - accuracy: 0.9773


[0.07551569491624832, 0.9772999882698059]

In [56]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [58]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.62394166e-08, 1.05232312e-08, 5.03057379e-07, 2.37427466e-05,
        2.28009777e-12, 1.69550248e-07, 4.32706679e-14, 9.99975085e-01,
        1.16445847e-07, 3.38927322e-07],
       [2.22529231e-08, 4.16696166e-05, 9.99940753e-01, 1.74555043e-05,
        9.02869576e-13, 9.23979293e-09, 1.05907416e-09, 2.63684474e-12,
        1.00586135e-07, 5.93129116e-13],
       [8.44244937e-07, 9.99155521e-01, 4.68760350e-04, 1.17474401e-05,
        1.52338107e-05, 4.48140236e-06, 7.45433454e-06, 2.07570905e-04,
        1.27691354e-04, 7.08026903e-07],
       [9.99969244e-01, 1.20631824e-10, 1.09200728e-05, 2.08570214e-07,
        1.88607530e-08, 1.24514700e-05, 7.02368084e-07, 4.02652176e-06,
        2.48973265e-07, 2.27308510e-06],
       [8.96934216e-06, 4.32822622e-09, 5.84647023e-05, 1.62494894e-06,
        9.68606830e-01, 8.10715210e-06, 6.04743855e-06, 2.54464569e-04,
        8.39711811e-06, 3.10471281e-02]], dtype=float32)>